### ISSUE TITLE
No data on the SUTD SenSing Website

### ISSUE THREAD

**Issue by jlneo** [SUTDMEC/SenseSG#5]
I think I managed to connect the device successfully, but under the "visualise data" on the SUTD SenSing Website, there is a message: "No errors while parsing". Does it mean that the data hasn't been transmitted successfully?

**Comment by sandrasiby** [comment]
Hello, 

That was a message put in by us to check that the webpage loaded successfully. It has been removed now. You will be able to visualize your data after the firmware update has taken place.

Regards,
Sandra
