### ISSUE TITLE
Can't find red LED near the connector

### ISSUE THREAD

**Issue by jlneo** [SUTDMEC/SenseSG#6]
I can't find the red LED near the connector when charging.

What happens if I accidentally connect to the black PCB?

**Comment by erikwilhelm** [comment]
You mean you plug in the micro USB in the connector on the green PCB as shown in the diagram, and the red LED doesn't light up?

An accidental connection to the black PCB is no problem, you just won't charge the battery that way.

**Comment by jlneo** [comment]
Yes, the red LED doesn't light up when I plug the microUSB in the connector on the green PCB. Not sure where the red LED is either.

**Comment by erikwilhelm** [comment]
This will be a nice 'hall of fame' issue - turns out the wiki refers to an old revision of the hardware with that LED. The currently distributed versions do not have that LED.
